### PR TITLE
[WIP] Page with auto-updating animated graphs

### PR DESCRIPTION
**Pull request by quinox**
**This is a work-in-progress** I'm filing this PR to collect some early feedback, the code shouldn't be actually merged at this point (there are no testcases yet fe.)

I really enjoyed SGDQ, and when I visited the website I saw the big list of donations but no pretty overview. When I discovered the site was built using Django I figured I'd help out a bit. I'm now working on an overview page that you can keep open while watching GDQ, showing the progress of the donations. It should be informative, pretty and fully animated.

Example

Already implemented:
- DB-code for efficiently generating the numbers using Django's `values`+`aggregate` (aggregation using `GROUP BY`)
- All graphs update (animated) when new stats are available. I'm using [D3](http://d3js.org/) to provide maximum flexibility in how the graphs look and behave.
- The donations total text is automatically updated (animated). This code can be applied to the regular donation listview donation amount as well. It counts "through", if the donations total increases by 1 dollar you'll also see the two cents digits flipping through, not just the dollar-digit.
- Fully bootstrap-compatible, the graphs are placed inside bootstrap columns and fill them up 
- A replay option, for debugging mainly. When pressing 'Replay' it will "wind back" time to show how the graph evolves over time from the beginning of the event (every 5 seconds progresses about 3 hours)
- The total-graphs (top graph) contains all previous GDQ event results and shows a target line when the current amount is nearby; when the current is under the target the line is orange, when the current total is over it changes to green. 

On the TODO list:
- Apply nice styling
- Implement wordcloud based on comments from the last X hours. 
- Remove the donation distribution graph as it's boring
- Add testcases
- Clean up code

### CODE REVIEW

**Comment by Hippocrates** [comment]
Hey, that looks pretty neat, and I think would be a very welcome addition. 

However, I will give fair warning: UraniumAnchor currently has plans to overhaul the set of front-facing pages using the react js framework, and thus at the point of merging, will probably require an extensive re-base.

**Comment by quinox** [comment]
Good to know, I'll make sure everything is clean, tidy and documented when I'm done.

Rebasing for react shouldn't be a problem, there's currently minimal templating involved.

**Comment by Hippocrates** [comment]
Not sure if you're still working on this or not, but just so you're aware we've moved the main repository over to https://github.com/GamesDoneQuick/donation-tracker

**Comment by quinox** [comment]
Thanks, I'll file my next PR over there. I was kind of waiting for the React change, it hasn't landed yet am I correct?

**Comment by Hippocrates** [comment]
Sort of. The beginnings of it are here (https://github.com/GamesDoneQuick/donation-tracker-ui), but right now we only have one specific back-end system implemented for it.

**Pull request closed without merging**
